INSERT INTO COIN(COIN_ID, CODE, COINNAME) VALUES (1, 'KRW-BTC', '비트코인');
INSERT INTO COIN(COIN_ID, CODE, COINNAME) VALUES (2, 'KRW-ETH', '이더리움');
INSERT INTO COIN(COIN_ID, CODE, COINNAME) VALUES (2, 'KRW-XRP', '리플');