INSERT INTO COIN(COIN_ID, CODE, COIN_NAME)
VALUES (1, 'KRW-BTC', '비트코인');
INSERT INTO COIN(COIN_ID, CODE, COIN_NAME)
VALUES (2, 'KRW-ETH', '이더리움');
INSERT INTO COIN(COIN_ID, CODE, COIN_NAME)
VALUES (3, 'KRW-XRP', '리플');